# Python Programming Assignment_8
------------------

#### 1. Write a Python Program to Add Two Matrices?

In [8]:
import numpy as np
x = np.random.randint(1,9,(3,3))
y = np.random.randint(1,9,(3,3))
x + y

array([[ 5,  6,  6],
       [ 6,  9, 10],
       [13, 14, 14]])

In [9]:
x

array([[3, 1, 1],
       [2, 4, 3],
       [6, 8, 6]])

In [10]:
y

array([[2, 5, 5],
       [4, 5, 7],
       [7, 6, 8]])

#### 2. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
x = np.random.randint(1,9,(3,3))
y = np.random.randint(1,9,(3,3))
x @ y

array([[37, 75, 75],
       [19, 49, 49],
       [20, 44, 44]])

In [3]:
x

array([[8, 5, 6],
       [7, 1, 2],
       [5, 2, 4]])

In [4]:
y

array([[2, 6, 6],
       [3, 3, 3],
       [1, 2, 2]])

#### 3. Write a Python Program to Transpose a Matrix?

In [5]:
import numpy as np
x = np.random.randint(1,9,(3,3))
x

array([[3, 7, 6],
       [6, 3, 3],
       [8, 4, 3]])

In [6]:
x.T

array([[3, 6, 8],
       [7, 3, 4],
       [6, 3, 3]])

#### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [23]:
s = input("Enter a sentence : ")
s1 = [i.lower() for i in s.split()]
s1.sort()
for i in s1:
    print(i, end="  ")

Enter a sentence : xnsm dm sbn abn
abn  dm  sbn  xnsm  

#### 5.  Write a Python Program to Remove Punctuation From a String?

In [18]:
Punctuation = '''~!@#$%^&*()_+{}:'":;<>,./?[]\|~`=-'''
s = input("Enter a sentence : ")
s1 = ""
for i in s:
    if i not in Punctuation:
        s1 += i
print(s1)

Enter a sentence : <ipython-input-13-7a1699fcbc58> in <module>
ipythoninput137a1699fcbc58 in module
